# -*- coding: utf-8 -*-
import sys
# Form implementation generated from reading ui file 'Add_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Main_Window
import openpyxl
import Warning_window
class Add_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(self.width(),self.height())
        self.check_list = []
        self.Account = ''
    def show(self) -> None:
        self.restore_choose()
        self.ban_some(self.check_list)
        super().show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(434, 468)
        self.Background_pic = QtWidgets.QLabel(Dialog)
        self.Background_pic.setGeometry(QtCore.QRect(-160, -10, 881, 521))
        self.Background_pic.setText("")
        self.Background_pic.setPixmap(QtGui.QPixmap("BackGround/Change.jpg"))
        self.Background_pic.setScaledContents(True)
        self.Background_pic.setObjectName("Background_pic")
        self.M249 = QtWidgets.QRadioButton(Dialog)
        self.M249.setGeometry(QtCore.QRect(70, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.M249.setFont(font)
        self.M249.setObjectName("M249")
        self.M416 = QtWidgets.QRadioButton(Dialog)
        self.M416.setGeometry(QtCore.QRect(240, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.M416.setFont(font)
        self.M416.setObjectName("M416")
        self.M16A4 = QtWidgets.QRadioButton(Dialog)
        self.M16A4.setGeometry(QtCore.QRect(70, 80, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.M16A4.setFont(font)
        self.M16A4.setObjectName("M16A4")
        self.AUG = QtWidgets.QRadioButton(Dialog)
        self.AUG.setGeometry(QtCore.QRect(240, 80, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AUG.setFont(font)
        self.AUG.setObjectName("AUG")
        self.AKM = QtWidgets.QRadioButton(Dialog)
        self.AKM.setGeometry(QtCore.QRect(70, 140, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AKM.setFont(font)
        self.AKM.setObjectName("AKM")
        self._98K = QtWidgets.QRadioButton(Dialog)
        self._98K.setGeometry(QtCore.QRect(240, 140, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self._98K.setFont(font)
        self._98K.setObjectName("_98K")
        self.Confirm = QtWidgets.QPushButton(Dialog)
        self.Confirm.setGeometry(QtCore.QRect(150, 270, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Confirm.setFont(font)
        self.Confirm.setObjectName("Confirm")
        self.Back = QtWidgets.QPushButton(Dialog)
        self.Back.setGeometry(QtCore.QRect(150, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")

        self.retranslateUi(Dialog)
        self.Back.clicked.connect(self.Back_to_main)
        self.Confirm.clicked.connect(self.confirm_clicked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add"))
        self.M249.setText(_translate("Dialog", "M249"))
        self.M416.setText(_translate("Dialog", "M416"))
        self.M16A4.setText(_translate("Dialog", "M16A4"))
        self.AUG.setText(_translate("Dialog", "AUG"))
        self.AKM.setText(_translate("Dialog", "AKM"))
        self._98K.setText(_translate("Dialog", "98K"))
        self.Confirm.setText(_translate("Dialog", "Confirm"))
        self.Back.setText(_translate("Dialog", "Back"))

    def ban_some(self,Have_gun : list):
        if str(self.AKM.text()) in Have_gun:
            self.AKM.setEnabled(False)
        if str(self.M416.text()) in Have_gun:
            self.M416.setEnabled(False)
        if str(self.M16A4.text()) in Have_gun:
            self.M16A4.setEnabled(False)
        if str(self.AUG.text()) in Have_gun:
            self.AUG.setEnabled(False)
        if str(self.M249.text()) in Have_gun:
            self.M249.setEnabled(False)
        if str(self._98K.text()) in Have_gun:
            self._98K.setEnabled(False)


    def restore_choose(self):
        self.M249.setEnabled(True)
        self.M416.setEnabled(True)
        self.M16A4.setEnabled(True)
        self.AKM.setEnabled(True)
        self.AUG.setEnabled(True)
        self._98K.setEnabled(True)

    def load_data(self,name):
        flag = 0
        data = [name]
        try:
            wb = openpyxl.load_workbook('./RootData/RootGun.xlsx')
            ws = wb['Weapon']
            row = 2
            while True:
                if str(ws.cell(row=row, column=1).value) != name:
                    row += 1
                    if row > 7:
                        break
                else:
                    for i in range(2,7):
                        data.append(ws.cell(row=row,column=i).value)
                    flag = 1
                    break
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if flag:
            wb = openpyxl.load_workbook('./UserData/' + self.Account + '/Weapon.xlsx')
            ws = wb["Weapon"]
            ws.cell(row=1, column=7).value = int(int(ws.cell(row=1, column=7).value) + 1)
            ws['A' + str(ws.cell(row=1,column=7).value)] = data[0]
            ws['B' + str(ws.cell(row=1, column=7).value)] = data[1]
            ws['C' + str(ws.cell(row=1, column=7).value)] = data[2]
            ws['D' + str(ws.cell(row=1, column=7).value)] = data[3]
            ws['E' + str(ws.cell(row=1, column=7).value)] = data[4]
            ws['F' + str(ws.cell(row=1, column=7).value)] = data[5]
            wb.save("./UserData/" + self.Account + "/Weapon.xlsx")

    def confirm_clicked(self):
        if self.AKM.isChecked():
            self.load_data('AKM')
        if self.M416.isChecked():
            self.load_data('M416')
        if self.AUG.isChecked():
            self.load_data('AUG')
        if self._98K.isChecked():
            self.load_data('98K')
        if self.M16A4.isChecked():
            self.load_data('M16A4')
        if self.M249.isChecked():
            self.load_data('M249')
        self.Back_to_main()

    def Back_to_main(self):
        self.main_window = Main_Window.Gun_MainWindow()
        flag = 0
        try:
            self.main_window.Welcome_player(self.Account)
            wb = openpyxl.load_workbook('./UserData/' + self.Account + '/Weapon.xlsx')
            ws = wb["Weapon"]
            data_list = []
            for i in range(int(ws.cell(row=1, column=7).value)):
                data = []
                for j in range(6):
                    data.append(str(ws.cell(row=i + 1, column=j + 1).value))
                data_list.append(data[0])
                self.main_window.Have_weapon = data_list
                self.main_window.weapom_display_add(name=data[0], Damage=int(data[1]), FiringMode=data[2],
                                                    capacity=int(data[3]), magazines=int(data[4]),
                                                    Bullets_remaining=int(data[5]))
            flag = 1
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if flag:
            self.main_window.show()
            self.deleteLater()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = Add_Dialog()
    w.show()
    sys.exit(app.exec_())