# -*- coding: utf-8 -*-
import sys
# Form implementation generated from reading ui file 'Change_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Main_Window
import os
import openpyxl
import Warning_window

class Ui_Change(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(self.width(),self.height())
        self.Account = ''
        self.Gun_name = ''
    def setupUi(self, Change):
        Change.setObjectName("Change")
        Change.resize(538, 468)
        self.Damage = QtWidgets.QLineEdit(Change)
        self.Damage.setGeometry(QtCore.QRect(70, 30, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Damage.setFont(font)
        self.Damage.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Damage.setObjectName("Damage")
        self.Damage.setInputMask("99")
        self.Magazine_capacity = QtWidgets.QLineEdit(Change)
        self.Magazine_capacity.setGeometry(QtCore.QRect(70, 100, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Magazine_capacity.setFont(font)
        self.Magazine_capacity.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Magazine_capacity.setObjectName("Magazine_capacity")
        self.Magazine_capacity.setInputMask("99")
        self.Magazines = QtWidgets.QLineEdit(Change)
        self.Magazines.setGeometry(QtCore.QRect(70, 170, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Magazines.setFont(font)
        self.Magazines.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Magazines.setObjectName("Magazines")
        self.Magazines.setInputMask("99")
        self.Bullets_remaining = QtWidgets.QLineEdit(Change)
        self.Bullets_remaining.setGeometry(QtCore.QRect(70, 240, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Bullets_remaining.setFont(font)
        self.Bullets_remaining.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Bullets_remaining.setObjectName("Bullets_remaining")
        self.Bullets_remaining.setInputMask("99")
        self.confirm_but = QtWidgets.QPushButton(Change)
        self.confirm_but.setGeometry(QtCore.QRect(60, 340, 151, 41))
        self.confirm_but.setStyleSheet("")
        self.confirm_but.setObjectName("confirm_but")
        self.Cancel_but = QtWidgets.QPushButton(Change)
        self.Cancel_but.setGeometry(QtCore.QRect(280, 340, 141, 41))
        self.Cancel_but.setObjectName("Cancel_but")
        self.Background_pic = QtWidgets.QLabel(Change)
        self.Background_pic.setGeometry(QtCore.QRect(-240, 0, 881, 521))
        self.Background_pic.setText("")
        self.Background_pic.setPixmap(QtGui.QPixmap("BackGround/Change.jpg"))
        self.Background_pic.setScaledContents(True)
        self.Background_pic.setObjectName("Background_pic")
        self.Background_pic.raise_()
        self.Damage.raise_()
        self.Magazine_capacity.raise_()
        self.Magazines.raise_()
        self.Bullets_remaining.raise_()
        self.confirm_but.raise_()
        self.Cancel_but.raise_()

        self.retranslateUi(Change)
        self.Cancel_but.clicked.connect(self.Back_to_main)
        self.confirm_but.clicked.connect(self.confirm_clicked)
        QtCore.QMetaObject.connectSlotsByName(Change)

    def retranslateUi(self, Change):
        _translate = QtCore.QCoreApplication.translate
        Change.setWindowTitle(_translate("Change", "Change"))
        self.Damage.setPlaceholderText(_translate("Change", "Damage"))
        self.Magazine_capacity.setPlaceholderText(_translate("Change", "Magazine_capacity"))
        self.Magazines.setPlaceholderText(_translate("Change", "Magazines"))
        self.Bullets_remaining.setPlaceholderText(_translate("Change", "Bullets_remaining"))
        self.confirm_but.setText(_translate("Change", "Confirm"))
        self.Cancel_but.setText(_translate("Change", "Cancel"))

    def confirm_clicked(self):
        if len(self.Damage.text()) == 0:
            self.Damage.setText("0")
        if len(self.Bullets_remaining.text()) == 0:
            self.Bullets_remaining.setText("0")
        if len(self.Magazine_capacity.text()) == 0:
            self.Magazine_capacity.setText("0")
        if len(self.Magazines.text()) == 0:
            self.Magazines.setText("0")
        try:
            wb = openpyxl.load_workbook('./UserData/' + self.Account + '/Weapon.xlsx')
            ws = wb["Weapon"]
            row = 1
            while True:
                if str(ws.cell(row=row,column=1).value) != self.Gun_name:
                    row += 1
                    if row > 6:
                        break
                else:
                    ws.cell(row=row,column=2).value = int(self.Damage.text())
                    ws.cell(row=row,column=4).value = int(self.Magazine_capacity.text())
                    ws.cell(row=row,column=5).value = int(self.Magazines.text())
                    ws.cell(row=row,column=6).value = int(self.Bullets_remaining.text())
                    wb.save("./UserData/" + self.Account + "/Weapon.xlsx")
                    break
            self.Back_to_main()
        except:
            self.er = Warning_window.Error()
            self.er.show()


    def Back_to_main(self):
        self.main_window = Main_Window.Gun_MainWindow()
        flag = 0
        try:
            self.main_window.Welcome_player(self.Account)
            wb = openpyxl.load_workbook('./UserData/' + self.Account + '/Weapon.xlsx')
            ws = wb["Weapon"]
            data_list = []
            for i in range(int(ws.cell(row=1, column=7).value)):
                data = []
                for j in range(6):
                    data.append(str(ws.cell(row=i + 1, column=j + 1).value))
                data_list.append(data[0])
                self.main_window.Have_weapon = data_list
                self.main_window.weapom_display_add(name=data[0], Damage=int(data[1]), FiringMode=data[2],
                                                    capacity=int(data[3]), magazines=int(data[4]),
                                                    Bullets_remaining=int(data[5]))
            flag = 1
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if flag:
            self.main_window.show()
            self.deleteLater()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = Ui_Change()
    win.show()
    sys.exit(app.exec_())