# -*- coding: utf-8 -*-
import sys
# Form implementation generated from reading ui file 'Login_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Signup_lab
import Signup_window
import Main_Window
import os
import Warning_window
import openpyxl

class Login_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(self.width(), self.height())
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 513)
        self.Login_lab = QtWidgets.QLabel(Dialog)
        self.Login_lab.setGeometry(QtCore.QRect(190, 40, 291, 61))
        font = QtGui.QFont()
        font.setFamily("\"Agency FB\"")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Login_lab.setFont(font)
        self.Login_lab.setStyleSheet("font: 24pt \\\"Agency FB\\\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 0,20,255 ), stop:1 rgba(0,0,255, 200));\n"
"\n"
"border-radius:15px;")
        self.Login_lab.setObjectName("Login_lab")
        self.BackGround = QtWidgets.QLabel(Dialog)
        self.BackGround.setGeometry(QtCore.QRect(0, 0, 761, 571))
        self.BackGround.setText("")
        self.BackGround.setPixmap(QtGui.QPixmap("BackGround/Login.jpg"))
        self.BackGround.setScaledContents(True)
        self.BackGround.setObjectName("BackGround")
        self.Account_input = QtWidgets.QLineEdit(Dialog)
        self.Account_input.setGeometry(QtCore.QRect(190, 130, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Account_input.setFont(font)
        self.Account_input.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Account_input.setClearButtonEnabled(True)
        self.Account_input.setObjectName("Account_input")
        self.confire_but = QtWidgets.QPushButton(Dialog)
        self.confire_but.setGeometry(QtCore.QRect(260, 310, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.confire_but.setFont(font)
        self.confire_but.setStyleSheet("")
        self.confire_but.setObjectName("confire_but")
        self.PassWord_input = QtWidgets.QLineEdit(Dialog)
        self.PassWord_input.setGeometry(QtCore.QRect(190, 220, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PassWord_input.setFont(font)
        self.PassWord_input.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.PassWord_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_input.setClearButtonEnabled(True)
        self.PassWord_input.setObjectName("PassWord_input")
        self.label = Signup_lab.Signup_label(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 450, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.BackGround.raise_()
        self.Login_lab.raise_()
        self.Account_input.raise_()
        self.confire_but.raise_()
        self.PassWord_input.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        self.label.clicked.connect(self.deleteLater)
        self.confire_but.clicked.connect(self.Confirm_account)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        self.Login_lab.setText(_translate("Dialog", "            Log   in"))
        self.Account_input.setPlaceholderText(_translate("Dialog", "Account"))
        self.confire_but.setText(_translate("Dialog", "Confirm"))
        self.PassWord_input.setPlaceholderText(_translate("Dialog", "PassWord"))
        self.label.setText(_translate("Dialog", "Have no account?"))

    def Confirm_account(self):
        flag = 0
        try:
            if os.path.exists("./UserData/"+self.Account_input.text()) and len(self.Account_input.text()):
                with open("./UserData/"+self.Account_input.text()+"/User.txt","r",encoding='utf-8')as fp:
                    if str(fp.read()) == str(self.PassWord_input.text()):
                        flag = 1
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if flag:
            self.Enter()
        else:
            self.er = Warning_window.Error()
            self.er.show()

    def Enter(self):
        self.main_window = Main_Window.Gun_MainWindow()
        self.main_window.Welcome_player(self.Account_input.text())
        flag = 0
        try:
            wb = openpyxl.load_workbook('./UserData/'+self.Account_input.text()+'/Weapon.xlsx')
            ws = wb["Weapon"]
            data_list = []
            for i in range(int(ws.cell(row=1,column=7).value)):
                data = []
                for j in range(6):
                    data.append(str(ws.cell(row=i+1,column=j+1).value))
                data_list.append(data[0])
                self.main_window.Have_weapon = data_list
                self.main_window.weapom_display_add(name=data[0],Damage=int(data[1]),FiringMode=data[2],capacity=int(data[3]),magazines=int(data[4]),Bullets_remaining=int(data[5]))
            flag = 1
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if flag:
            self.main_window.show()
            self.deleteLater()



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Login_Dialog()
    window.show()
    sys.exit(app.exec_())