# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Add_weapon_but
import Weapon_window
import Login_Window

class Gun_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.Have_weapon = []
        self.setupUi(self)
        self.setFixedSize(self.width(), self.height())
    def Welcome_player(self,Player_name : str):
        self.Welcome.setText("Welcome back!  " + Player_name)
        self.PlayerName = Player_name
        self.Add_Weapon.AddWeapon.Account = self.PlayerName
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gun_Display = QtWidgets.QTabWidget(self.centralwidget)
        self.Gun_Display.setGeometry(QtCore.QRect(0, 90, 801, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(17)
        sizePolicy.setHeightForWidth(self.Gun_Display.sizePolicy().hasHeightForWidth())
        self.Gun_Display.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Gun_Display.setFont(font)
        self.Gun_Display.setStyleSheet("\n"
"background-color: rgb(191, 191, 191);")
        self.Gun_Display.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Gun_Display.setIconSize(QtCore.QSize(30, 30))
        self.Gun_Display.setElideMode(QtCore.Qt.ElideNone)
        self.Gun_Display.setUsesScrollButtons(True)
        self.Gun_Display.setMovable(True)
        self.Gun_Display.setObjectName("Gun_Display")
        self.Welcome = QtWidgets.QLabel(self.centralwidget)
        self.Welcome.setGeometry(QtCore.QRect(11, 11, 771, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Welcome.sizePolicy().hasHeightForWidth())
        self.Welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("\"Agency FB\"")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Welcome.setFont(font)
        self.Welcome.setStyleSheet("font: 24pt \\\"Agency FB\\\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 0,20,255 ), stop:1 rgba(0,0,255, 200));\n"
"border-radius:15px;\n"
"")
        self.Welcome.setObjectName("Welcome")
        self.Back_but = QtWidgets.QPushButton(self.centralwidget)
        self.Back_but.setGeometry(QtCore.QRect(110, 510, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.Back_but.sizePolicy().hasHeightForWidth())
        self.Back_but.setSizePolicy(sizePolicy)
        self.Back_but.setStyleSheet("")
        self.Back_but.setObjectName("Back_but")
        self.Quit_but = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_but.setGeometry(QtCore.QRect(580, 510, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.Quit_but.sizePolicy().hasHeightForWidth())
        self.Quit_but.setSizePolicy(sizePolicy)
        self.Quit_but.setMinimumSize(QtCore.QSize(50, 0))
        self.Quit_but.setObjectName("Quit_but")
        self.BackGround_pic = QtWidgets.QLabel(self.centralwidget)
        self.BackGround_pic.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.BackGround_pic.setText("")
        self.BackGround_pic.setPixmap(QtGui.QPixmap("BackGround/Main.jpg"))
        self.BackGround_pic.setScaledContents(True)
        self.BackGround_pic.setWordWrap(False)
        self.BackGround_pic.setObjectName("BackGround_pic")
        self.Add_Weapon = Add_weapon_but.Add_weapon_button(self.centralwidget)
        self.Add_Weapon.setGeometry(QtCore.QRect(340, 510, 111, 31))
        self.Add_Weapon.setObjectName("Add_Weapon")
        self.BackGround_pic.raise_()
        self.Gun_Display.raise_()
        self.Welcome.raise_()
        self.Back_but.raise_()
        self.Quit_but.raise_()
        self.Add_Weapon.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Quit_but.clicked.connect(self.Exit)
        self.Back_but.clicked.connect(self.Back_to_login)
        self.Gun_Display.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Welcome.setText(_translate("MainWindow", "Welcome back! Player"))
        self.Back_but.setText(_translate("MainWindow", "Back to login"))
        self.Quit_but.setText(_translate("MainWindow", "Quit"))
        self.Add_Weapon.setText(_translate("MainWindow", "Add Weapon"))

    def Back_to_login(self):
        self.login = Login_Window.Login_Dialog()
        self.login.show()
        self.deleteLater()

    def Exit(self):
        sys.exit(0)

    def weapom_display_add(self,Damage : int,FiringMode : str,capacity : int,magazines : int,Bullets_remaining : int,name : str):
        weapon = Weapon_window.Weapon_win()
        weapon.Change_but.Change_.Account = str(self.PlayerName)
        weapon.set_Damage(Damage)
        weapon.set_FiringMode(FiringMode)
        weapon.set_Magazine_capacity(capacity)
        weapon.set_magazines(magazines)
        weapon.set_Bullets_remaining(Bullets_remaining)
        weapon.Change_but.Change_.Gun_name = name
        weapon.Delete_but.Gun_name = name
        weapon.Delete_but.Account = str(self.PlayerName)
        path = ".\\Gun_Icon\\" + name + ".jpg"
        weapon.set_pic(path)
        self.Add_Weapon.AddWeapon.check_list = self.Have_weapon
        self.Gun_Display.addTab(weapon,name)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Gun_MainWindow()
    window.show()
    sys.exit(app.exec_())