# -*- coding: utf-8 -*-
import sys
# Form implementation generated from reading ui file 'Signup_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
import Login_Window
import Warning_window
from openpyxl import Workbook

class Signup_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setFixedSize(self.width(), self.height())
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(693, 515)
        self.BackGround = QtWidgets.QLabel(Dialog)
        self.BackGround.setGeometry(QtCore.QRect(0, 0, 761, 571))
        self.BackGround.setText("")
        self.BackGround.setPixmap(QtGui.QPixmap("BackGround/Login.jpg"))
        self.BackGround.setScaledContents(True)
        self.BackGround.setObjectName("BackGround")
        self.Login_lab = QtWidgets.QLabel(Dialog)
        self.Login_lab.setGeometry(QtCore.QRect(180, 30, 291, 61))
        font = QtGui.QFont()
        font.setFamily("\"Agency FB\"")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Login_lab.setFont(font)
        self.Login_lab.setStyleSheet("font: 24pt \\\"Agency FB\\\";\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 0,20,255 ), stop:1 rgba(0,0,255, 200));\n"
"\n"
"border-radius:15px;")
        self.Login_lab.setObjectName("Login_lab")
        self.Account_input = QtWidgets.QLineEdit(Dialog)
        self.Account_input.setGeometry(QtCore.QRect(180, 100, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Account_input.setFont(font)
        self.Account_input.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.Account_input.setClearButtonEnabled(True)
        self.Account_input.setObjectName("Account_input")
        self.PassWord_input = QtWidgets.QLineEdit(Dialog)
        self.PassWord_input.setGeometry(QtCore.QRect(180, 180, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PassWord_input.setFont(font)
        self.PassWord_input.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.PassWord_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_input.setClearButtonEnabled(True)
        self.PassWord_input.setObjectName("PassWord_input")
        self.PassWord_input_2 = QtWidgets.QLineEdit(Dialog)
        self.PassWord_input_2.setGeometry(QtCore.QRect(180, 260, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PassWord_input_2.setFont(font)
        self.PassWord_input_2.setStyleSheet("QLineEdit{border-radius:15px;}")
        self.PassWord_input_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord_input_2.setClearButtonEnabled(True)
        self.PassWord_input_2.setObjectName("PassWord_input_2")
        self.confire_but = QtWidgets.QPushButton(Dialog)
        self.confire_but.setGeometry(QtCore.QRect(240, 370, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.confire_but.setFont(font)
        self.confire_but.setStyleSheet("")
        self.confire_but.setObjectName("confire_but")
        self.back_but = QtWidgets.QPushButton(Dialog)
        self.back_but.setGeometry(QtCore.QRect(240, 420, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.back_but.setFont(font)


        self.retranslateUi(Dialog)
        self.back_but.clicked.connect(self.Back_to_login)
        self.confire_but.clicked.connect(self.check_exit)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Signup"))
        self.Login_lab.setText(_translate("Dialog", "            Sign  up"))
        self.Account_input.setPlaceholderText(_translate("Dialog", "Account"))
        self.PassWord_input.setPlaceholderText(_translate("Dialog", "PassWord"))
        self.PassWord_input_2.setPlaceholderText(_translate("Dialog", "Confirm PassWord"))
        self.confire_but.setText(_translate("Dialog", "Confirm"))
        self.back_but.setText(_translate("Dialog","Back"))

    def Back_to_login(self):
        self.login = Login_Window.Login_Dialog()
        self.login.show()
        self.deleteLater()

    def check_exit(self):
        fg = 0
        try:
            if  (not os.path.exists("./UserData/"+self.Account_input.text())) and self.PassWord_input.text() == self.PassWord_input_2.text() and len(self.PassWord_input.text()):
                os.mkdir("./UserData/" + self.Account_input.text())
                with open("./UserData/" + self.Account_input.text() + "/User.txt", "w", encoding='utf-8') as fp:
                    fp.write(self.PassWord_input.text())
                wb = Workbook()
                ws = wb.create_sheet("Weapon")
                wb.remove(wb["Sheet"])
                ws['G1'] = int(0)
                wb.save("./UserData/"+self.Account_input.text()+"/Weapon.xlsx")
                fg = 1
                self.Back_to_login()
                self.succeed = Warning_window.Signup_succeed()
                self.succeed.show()
        except:
            self.er = Warning_window.Error()
            self.er.show()
        if fg:
            pass
        elif os.path.exists("./UserData/"+self.Account_input.text()):
            self.Rename = Warning_window.Account_Dialog()
            self.Rename.show()
        else:
            self.er = Warning_window.Error()
            self.er.show()




if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Signup_Dialog()
    window.show()
    sys.exit(app.exec_())